### PR TITLE
Create E-commerce website design.md

### PR DESCRIPTION
**Pull request by Khushi-design-20**
Graphic UI design for an E-commerce store.

(Pls add the hacktoberfest-accepted tag before merging if you like it, thanks!)

### CODE REVIEW

**Comment by Khushi-design-20** [comment]
@Girlwithasmile 
Pls add the hacktoberfest-accepted tag before merging if you like it, thanks!

**Comment by Girlwithasmile** [comment]
Hey.. can you create the graphic designs folder again, add both designs and create another pull request. I am adding tag to this pr as of now, this tag shall be removed when you create that pr.

**Comment by Khushi-design-20** [comment]
I have 3-4 more designs, I should upload them one-by-one I guess so that
all get counted. Does that sound okay?

**Comment by Girlwithasmile** [comment]
Yep upload them one by one..

**Pull request closed without merging**
