### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Khushi-design-20**
Issue #1
Added hacktoberfest labels, fixed some typos and grammatical errors, and added a tech-stack table.

### CODE REVIEW

**Comment by Girlwithasmile** [comment]
Can u just add a good small hackthoberfest image? Rest is good.

**Comment by Khushi-design-20** [comment]
Added ✔️

**Comment by Khushi-design-20** [comment]
Hey, I just noticed your repo doesn't have the "hacktoberfest" tag.
It's misspelt. pls, check it!

**Comment by Girlwithasmile** [comment]
> Hey, I just noticed your repo doesn't have the "hacktoberfest" tag. It's misspelt. pls, check it!

Ok sure thanks for this...!

**Comment by Girlwithasmile** [comment]
Thank you for your contribution!

**Pull request merged**
